# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createnew.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class CreatUi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 90, 601, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.proname = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.proname.setObjectName("proname")
        self.gridLayout.addWidget(self.proname, 0, 3, 1, 1)
        self.pronumber = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.pronumber.setObjectName("pronumber")
        self.gridLayout.addWidget(self.pronumber, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1, QtCore.Qt.AlignRight)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.dutyname = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.dutyname.setObjectName("dutyname")
        self.gridLayout.addWidget(self.dutyname, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1, QtCore.Qt.AlignRight)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.proaccount = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.proaccount.setObjectName("proaccount")
        self.gridLayout.addWidget(self.proaccount, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1, QtCore.Qt.AlignRight)
        self.receiveaccount = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.receiveaccount.setObjectName("receiveaccount")
        self.gridLayout.addWidget(self.receiveaccount, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 2, 1, 1)
        self.payaccount = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.payaccount.setObjectName("payaccount")
        self.gridLayout.addWidget(self.payaccount, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 4, 1, 1)
        self.prodate = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.prodate.setObjectName("prodate")
        self.gridLayout.addWidget(self.prodate, 1, 5, 1, 1)
        self.receivedate = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.receivedate.setObjectName("receivedate")
        self.gridLayout.addWidget(self.receivedate, 3, 3, 1, 1)
        self.paydate = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.paydate.setObjectName("paydate")
        self.gridLayout.addWidget(self.paydate, 4, 3, 1, 1)
        self.protype = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.protype.setObjectName("protype")
        self.protype.addItem("")
        self.protype.addItem("")
        self.protype.addItem("")
        self.gridLayout.addWidget(self.protype, 0, 5, 1, 1)
        self.accounttype = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.accounttype.setObjectName("accounttype")
        self.accounttype.addItem("")
        self.accounttype.addItem("")
        self.accounttype.addItem("")
        self.accounttype.addItem("")
        self.accounttype.addItem("")
        self.accounttype.addItem("")
        self.accounttype.addItem("")
        self.accounttype.addItem("")
        self.accounttype.addItem("")
        self.gridLayout.addWidget(self.accounttype, 2, 3, 1, 1)
        self.apartment = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.apartment.setObjectName("apartment")
        self.apartment.addItem("")
        self.apartment.addItem("")
        self.apartment.addItem("")
        self.apartment.addItem("")
        self.apartment.addItem("")
        self.gridLayout.addWidget(self.apartment, 1, 3, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 10, 601, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title, 0, QtCore.Qt.AlignHCenter)
        self.sucessButton = QtWidgets.QPushButton(self.centralwidget)
        self.sucessButton.setGeometry(QtCore.QRect(260, 520, 75, 23))
        self.sucessButton.setObjectName("sucessButton")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(340, 520, 75, 23))
        self.clearButton.setObjectName("clearButton")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(420, 520, 75, 23))
        self.closeButton.setObjectName("closeButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "项目编号："))
        self.label_5.setText(_translate("MainWindow", "项目名称："))
        self.label_2.setText(_translate("MainWindow", "类型："))
        self.label_3.setText(_translate("MainWindow", "责任人："))
        self.label_6.setText(_translate("MainWindow", "部门："))
        self.label_4.setText(_translate("MainWindow", "合同金额："))
        self.label_7.setText(_translate("MainWindow", "币种："))
        self.label_8.setText(_translate("MainWindow", "收款金额："))
        self.label_9.setText(_translate("MainWindow", "收款日期："))
        self.label_11.setText(_translate("MainWindow", "付款日期："))
        self.label_10.setText(_translate("MainWindow", "付款金额："))
        self.label_13.setText(_translate("MainWindow", "签订日期："))
        self.protype.setItemText(0, _translate("MainWindow", "销售合同"))
        self.protype.setItemText(1, _translate("MainWindow", "采购合同"))
        self.protype.setItemText(2, _translate("MainWindow", "其他"))
        self.accounttype.setItemText(0, _translate("MainWindow", "人民币"))
        self.accounttype.setItemText(1, _translate("MainWindow", "美金"))
        self.accounttype.setItemText(2, _translate("MainWindow", "港元"))
        self.accounttype.setItemText(3, _translate("MainWindow", "台币"))
        self.accounttype.setItemText(4, _translate("MainWindow", "英镑"))
        self.accounttype.setItemText(5, _translate("MainWindow", "欧元"))
        self.accounttype.setItemText(6, _translate("MainWindow", "卢布"))
        self.accounttype.setItemText(7, _translate("MainWindow", "日元"))
        self.accounttype.setItemText(8, _translate("MainWindow", "韩元"))
        self.apartment.setItemText(0, _translate("MainWindow", "商务部"))
        self.apartment.setItemText(1, _translate("MainWindow", "咨询部"))
        self.apartment.setItemText(2, _translate("MainWindow", "项目部"))
        self.apartment.setItemText(3, _translate("MainWindow", "营销中心"))
        self.apartment.setItemText(4, _translate("MainWindow", "行政部"))
        self.title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">新建合同信息填写</span></p></body></html>"))
        self.sucessButton.setText(_translate("MainWindow", "保存"))
        self.clearButton.setText(_translate("MainWindow", "重置"))
        self.closeButton.setText(_translate("MainWindow", "取消"))

